name: app_municipalidad_sb
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.6.3
  shared_preferences: ^2.3.3
  flutter_bloc: ^9.0.0
  loader_overlay: ^4.0.4+1
  quickalert: ^1.1.0
  url_launcher: ^6.3.1
  avatar_glow: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/imgs/
    - assets/imgs/login/
    - assets/imgs/inicio/
    - assets/imgs/inicio/denuncias/
    - assets/imgs/inicio/emergencias/
    - assets/imgs/inicio/emergencias/alertas/
    - assets/imgs/inicio/navigation/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Black.ttf
        - asset: assets/fonts/Raleway-BlackItalic.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-BoldItalic.ttf

  uses-material-design: true

